import {
  Activity,
  AtSign,
  Baby,
  BadgeCheck,
  Briefcase,
  Building,
  Cake,
  Cigarette,
  Coffee,
  Crown,
  Dog,
  FileText,
  GraduationCap,
  Hash,
  Heart,
  HeartHandshake,
  Languages,
  Mail,
  MapPin,
  MessageSquare,
  PieChart,
  Radar,
  Ruler,
  Scale,
  Search,
  Star,
  ThumbsUp,
  User,
  UserCheck,
  UserPlus,
  Wine,
} from 'lucide-react'

const MAP = {
  user: User,
  heart: Heart,
  ruler: Ruler,
  scale: Scale,
  briefcase: Briefcase,
  building: Building,
  'graduation-cap': GraduationCap,
  star: Star,
  baby: Baby,
  cigarette: Cigarette,
  wine: Wine,
  'heart-handshake': HeartHandshake,
  languages: Languages,
  'user-check': UserCheck,
  activity: Activity,
  'file-text': FileText,
  'thumbs-up': ThumbsUp,
  hash: Hash,
  mail: Mail,
  'badge-check': BadgeCheck,
  crown: Crown,
  coffee: Coffee,
  instagram: AtSign,
  search: Search,
  dog: Dog,
  'pie-chart': PieChart,
  'user-plus': UserPlus,
  'map-pin': MapPin,
  cake: Cake,
  'message-square': MessageSquare,
  radar: Radar,
}

export function ProfileFieldIcon({ name, size = 16 }) {
  const Cmp = MAP[name] || Hash
  return <Cmp size={size} aria-hidden className="profile-field-lucide" />
}
